p2p: reduce log severity
tendermint/tendermint pull request #5338
Opened 2020-09-07 17:06 UTC by marbar3778

## Description

This PR aims to reduce the amount of `Logger.Error(..)` calls. Many of these calls are benign and do not need any intervention. 

There are a few that could be debated to be logged as an Error or not. 

Closes: #4937

2020-09-08 07:57 UTC, marbar3778 commented on p2p/switch.go
> +			sw.Logger.Debug("Error while stopped reactor", "reactor", reactor, "error", err)
```suggestion
			sw.Logger.Debug("Error while stopping reactor", "reactor", reactor, "error", err)
```

2020-09-08 11:33 UTC, erikgrinaker reviewed
I think this is too zealous, and many of these should remain errors. A good place to start would be to run a testnet and stop/start a few nodes, then see which error messages are emitted and silence the ones that are too noisy or misleading.

2020-09-08 12:16 UTC, marbar3778 commented
> I think this is too zealous, and many of these should remain errors. A good place to start would be to run a testnet and stop/start a few nodes, then see which error messages are emitted and silence the ones that are too noisy or misleading.

I was coming from the perspective of a node operator on what information I would like to see. It is a bit overzealous, will reduce it.

2020-09-09 09:38 UTC, erikgrinaker requested changes
Minor comment, otherwise looks good.

2020-09-09 09:38 UTC, erikgrinaker commented on p2p/conn/connection.go
> +			c.Logger.Debug("Connection failed @ recvRoutine", "conn", c, "err", err)
This should probably remain an error, since we received an unknown message type.

2020-09-09 09:56 UTC, erikgrinaker approved these changes

2020-09-09 10:21 UTC, merged