cmd: add support for --key
tendermint/tendermint pull request #5612
Opened 2020-11-03 16:10 UTC by marbar3778

## Description

add support for `--key` on various flags for picking between ed25519 & secp256k1 curves in privval

Closes: #5603

2020-11-04 14:55 UTC, marbar3778 commented on test/e2e/pkg/manifest.go
> +	KeyType string `toml:"key_type"`
For now this is used to set all keys of a validator. I did some testing, using two different curves caused some issues. Need to look deeper into it.

2020-11-05 15:10 UTC, erikgrinaker commented on test/e2e/networks/single_secp.toml
> +key_type = "secp256k1"
I'm guessing this was just used while testing, I think we can just drop committing these since they are trivial to set up again if needed.

2020-11-05 15:10 UTC, erikgrinaker commented on test/e2e/pkg/testnet.go
> +	}
This should be a switch. Also, seed generation code is the same across key types.

2020-11-05 15:10 UTC, erikgrinaker commented on test/e2e/pkg/testnet.go
> +	KeyType          string
We need to validate this in `Validate()`.

2020-11-09 06:25 UTC, melekes requested changes
👍

2020-11-09 06:25 UTC, melekes commented on privval/file.go
> +		return nil, fmt.Errorf("key type: %T is not supported", keyType)
```suggestion
		return nil, fmt.Errorf("key type: %s is not supported", keyType)
```

2020-11-09 06:25 UTC, melekes commented on test/e2e/runner/setup.go
> +		return genesis, errors.New("unsupported doc")
```suggestion
		return genesis, errors.New("unsupported KeyType")
```

2020-11-09 06:25 UTC, melekes commented on test/e2e/pkg/testnet.go
> +		return errors.New("unsupported keyType")
```suggestion
		return errors.New("unsupported KeyType")
```

2020-11-09 06:25 UTC, melekes commented on test/e2e/pkg/testnet.go
> +		panic("Keytype not supported") // should not make it this far
```suggestion
		panic("KeyType not supported") // should not make it this far
```

2020-11-09 12:14 UTC, melekes commented on privval/file.go
> +	case "", "ed25519":
define const for these?

2020-11-09 14:20 UTC, melekes approved these changes

2020-11-09 14:22 UTC, merged