abci: replace Mutex to RWMutex for better concurrency
tendermint/tendermint pull request #6173
Opened 2021-02-24 04:51 UTC by hanjukim

Improves concurrency by making Info and Query methods to use read lock.

Closes #6048

2021-02-24 07:23 UTC, marbar3778 reviewed
Looks good. Could you add a Changelog please.

2021-02-24 07:45 UTC, melekes requested changes
Thank you @hanjukim 👍 While I support the change, this could be breaking for some ABCI applications, so we need to document the requirements in https://github.com/tendermint/spec/blob/master/spec/abci/client-server.md when using the local client. 

Also, do we want to make the same changes in the socket server (abci/server/socket_server.go)?

See a larger discussion https://github.com/tendermint/tendermint/discussions/6171

2021-02-26 09:10 UTC, hanjukim commented
we found a problem from launchpad. I will report the information soon.

2021-03-14 00:42 UTC, closed without merging

2021-03-31 22:14 UTC, alexanderbez commented
@hanjukim what was the issue you found? Is it still possible to use a read-lock?

2021-04-01 12:12 UTC, hanjukim commented
@alexanderbez It seems to work with https://github.com/terra-project/cosmos-sdk/commit/facf3b16313176bc2aabe69503a71a2e4046c828, but we were too worried to apply this in production. Since major slow downs are caused by IAVL, this can help but not significant impact as we expect.