p2p: fix network update test
tendermint/tendermint pull request #6361
Opened 2021-04-16 15:53 UTC by tychoish

The test really just needs to assert that the proper updatese are
sent, I think having extra updates in the channel when the tests are
over isn't really a problem in this case.

2021-04-16 16:43 UTC, cmwaters approved these changes

2021-04-16 18:18 UTC, alexanderbez requested changes

2021-04-16 18:18 UTC, alexanderbez commented on p2p/p2ptest/network.go
> +func (n *Node) MakePeerUpdatesWithoutCleanup(t *testing.T) *p2p.PeerUpdates {
Not sure this is the ideal method name IMHO. We're still running cleanup.

2021-04-19 22:00 UTC, alexanderbez approved these changes
🌮

2021-04-19 22:02 UTC, merged