service: remove close signal channels
tendermint/tendermint pull request #7384
Opened 2021-12-06 18:38 UTC by tychoish

2021-12-06 19:04 UTC, creachadair approved these changes

2021-12-06 22:44 UTC, williambanfield requested changes

2021-12-06 22:44 UTC, williambanfield commented on internal/mempool/reactor_test.go
> +		if len(txs) == pool.Size() {
Why this change?

2021-12-06 22:44 UTC, williambanfield commented on internal/p2p/peermanager.go
> +		// We have to check doneCHan separately first, otherwise there's a 50%
```suggestion
		// We have to check doneCh separately first, otherwise there's a 50%
```

2021-12-06 22:44 UTC, williambanfield commented on internal/p2p/transport_mconn.go
> +	if m.hasFinished {
This is a data race with `Close`

2021-12-06 22:44 UTC, williambanfield commented on internal/p2p/transport_memory.go
> +	if t.isClosed {
Similarly a data race.

2021-12-07 13:34 UTC, tychoish commented
Going to split up this change into, hopefully mergeable components.

2021-12-07 14:47 UTC, closed without merging